print (" Use python3")
noun = input ("Input a noun: ")
adjective = input ("input your adjective: ")
food = input ("input your favourite food: ")
food1 = input ("input another food name: ")
color = input("input your favourite color: ")
color1 = input("input another favourite color: ")
part_of_body = input("input a party of body: ")
verb = input("input a verb: ")
verb_ing = input("input a verb-ing: ")
animal = input ("input your favourite animal name: ")
animal1 = input ("input your another favourite animal name: ")

print ("                                                        ")
print ("                                                        ")
print (" ------------------------------------------------------")
print ("|                Madness overloaded                    |")
print (" ------------------------------------------------------")
print ("                                                        ")
print ("our "+ noun + " are packed for a hike in the "+adjective )
print ("Mountains! we are carring a picnic lunch with ")
print (food + " and " + food1 + " on our " +part_of_body+ " and i " )
print ("have a "+noun+ " for "+verb_ing+ " photos, we will " + verb)
print ("past meadows filled with "+color+" and "+color1 )
print ("folowers, and pass a "+adjective+" waterfall that ")
print ("sounds like a "+noun+ " , many animals live in the ")
print ("Mountains, like the "+adjective+" "+ animal+ " and")
print (adjective+" " + animal1+" .it's fun to "+verb+ " them")
print ("but important to be safe and keep a "+ adjective)
print ("distance. the higher we "+verb+ " the smaller")
print ("the windflower meadow and waterfall appear; ")
print ("we may even see "+noun+ " still on the ground ")
print("from the last winter.")
print("")
print ("Share and tweet if you like it, twitter_handle :- raj_singh_ch ")